blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('',views.all_blogs,name='all_blogs'),
    path('<int:blog_id>/',views.detail,name='detail')
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('blog/', include('blog.urls')),
]
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Post(models.Model):
    titlePost = models.CharField(max_length=200)
    datePost = models.DateField()
    contentPost = models.TextField()

    def __str__(self):
        return self.titlePost

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

def all_blogs(request):
    cantPosts = Post.objects.count
    posts = Post.objects.order_by('-datePost')[:3]
    tituloPagina = ' Blog de Álvaro - Todos mis Posts'
    cantidadPosts = 3
    return render(request,'blog/all_blogs.html',{'posts':posts,'cantPosts':cantidadPosts,'tituloPagina':tituloPagina})

def detail(request,blog_id):
    blog = get_object_or_404(Post, pk=blog_id)
    tituloPagina = ' Blog de Álvaro - '+blog.titlePost
    return render(request,'blog/detail.html',{'blog':blog,'tituloPagina':tituloPagina})

portfolio/views.py
from django.shortcuts import render
from .models import Project
from django.http import HttpResponse
import random

def home(request):
    projects = Project.objects.order_by('-id')[:3]
    tituloPagina = 'Portfolio - Todos mis proyectos'
    return render(request,'portfolio/home.html',{'projects':projects,'tituloPagina':tituloPagina})

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}
{% block content %}
<div class="content text-center">
<h1>Blog</h1>
<h5>Álvaro ha escrito {{ cantPosts }} post{{ cantPosts|pluralize }}</h5>
</div>
<div class="container">
{% for post in posts %}
<hr \>
<h1><a href="{% url 'blog:detail' post.id  %}">{{ post.titlePost }}</a></h1>
<h5>{{ post.datePost|date:'d M Y'|upper }}</h5>
<h2>{{ post.contentPost|striptags|truncatewords:10 }}</h2>
{% endfor %}
</div>
{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}
{% block content %}
<div class="content text-center">
<h1 class="text-center mt-5" id="blogdetailtitle">{{ blog.titlePost }}</h1>
</div>
<div class="container">
<a href="{% url 'blog:all_blogs' %}">Volver al Blog</a>
<hr \>
<h5>{{ blog.datePost|date:'d M Y'|upper }}</h5>
<h2>{{ blog.contentPost|safe }}</h2>
<hr \>
<a href="{% url 'blog:all_blogs' %}">Volver al Blog</a>
</div>
{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">
    <link rel="icon" type="image/png" href="{% static 'portfolio/logoaa.png' %}">
    <title>{{ tituloPagina }}</title>
  </head>
  <body>
    <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">
          <img src="{% static "portfolio/logoaa.png" %}" width="100" class="d-inline-block align-top" alt="Alvaro Aguilar Logo">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-center" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <!-- <li class="nav-item">
              <a class="nav-link" href="{% static " portfolio/resume.pdf" %}">Resume</a>
            </li> -->
            <li class="nav-item">
              <a class="nav-link" href="https://www.linkedin.com/in/alvaro-aguilar-43356792/" target="_blank">LinkedIn</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://twitter.com/alvaroaguilar_" target="_blank">Twitter</a>
            </li>
            <li>
              <a role="button" href="{% url 'blog:all_blogs' %}" class="btn btn-primary">Blog</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

{% block content %} {% endblock%}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% block content %}
<div class="container">
<div class="content text-center">
<h1>Portfolio de Álvaro</h1>
{% load static %}
<br \><img src="{% static 'portfolio/clan.png' %}" class="img-fluid">
</div>
<hr/>
<ul class="flex-container">
{% for project in projects %}
   <li class="flex-item">
    <h2>{{ project.title }}</h2>
    <h5>{{ project.description|truncatechars:80 }}</h5>
    <img src="{{ project.image.url }}" class="img-fluid" width="100%">
    {% if project.url %}
    <br><a href="{{ project.url }}" target="_blank">Ver sitio</a>
  </li>
{% endif %}
{% endfor %}
</ul>
<hr/>
</div>
{% endblock %}